#!/usr/bin/env sh
docker run -d \
  -e POSTGRES_DB=langchain-rust \
  -e POSTGRES_USER=username \
  -e POSTGRES_PASSWORD=password \
  -e PGDATA=/var/lib/postgresql/data/pgdata \
  -v pgvolume-langchain-rust:/var/lib/postgresql/data \
  -p 5432:5432 \
  --name pgvector \
  pgvector/pgvector:pg16
